### ISSUE TITLE
Socket is closed

### ISSUE THREAD

**Issue by fusionbeam** [andywer/pg-listen#10]
Hi,

I am trying to run a node based on your Usage instructions but I get a socket is closed error.
Not sure I am doing it right as it looks like the process on exit handler is called prematurely.

Here is my code:
```
import createSubcriber from "pg-listen"
import { databaseURL } from "./config"

// Accepts the same connection config object that the "pg" package would take
const subscriber = createSubcriber({ connectionString: databaseURL });

subscriber.notifications.on("my-channel", (payload) => {
  // Payload as passed to subscriber.notify() (see below)
  console.log("Received notification in 'my-channel':", payload)
})

subscriber.events.on("error", (error) => {
  console.error("Fatal database connection error:", error)
  process.exit(1)
})

process.on("exit", () => {
  console.log('Process on exit has been called');
  subscriber.close()
})

export async function connect () {
  console.log('connect called')
  await subscriber.connect()
  await subscriber.listenTo("my-channel")
}

export async function sendSampleMessage () {
  console.log('sending a notify message to postgres');
  await subscriber.notify({
    greeting: "Hey, buddy.",
    timestamp: Date.now()
  })
}
```

I am running `export DEBUG=pg-listen:*; node dist/index.js`
Console output is:
```
pg-listen:connection Creating PostgreSQL client for notification streaming +0ms
Process on exit has been called
  pg-listen:connection Closing PostgreSQL notification listener. +6ms
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:711:18)
    at Socket._write (net.js:733:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Connection.end (/Users/ra/code/popmetrics/pig/database-notifier/node_modules/pg/lib/connection.js:320:22)
    at Client.end (/Users/ra/code/popmetrics/pig/database-notifier/node_modules/pg/lib/client.js:489:21)
    at Object.close (/Users/ra/code/popmetrics/pig/database-notifier/node_modules/pg-listen/dist/index.js:240:29)
    at process.<anonymous> (/Users/ra/code/popmetrics/pig/database-notifier/dist/index.js:33:14)
    at process.emit (events.js:197:13)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:98:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:618:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at Socket._writeGeneric (net.js:711:10)
    at Socket._write (net.js:733:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
```

The database connection is fine and tested.

**Comment by fusionbeam** [comment]
figured it out on my own.
rookie mistake
```
subscriber.connect();
subscriber.listenTo('my-channel');
```
to keep the process up and running.

also the payload must be a json string.

**Comment by andywer** [comment]
Good to see you figured it out already!

The payload doesn't need to be a JSON string, though. It can be anything JSON-serializable. See [`test/integration.test.ts`](https://github.com/andywer/pg-listen/blob/master/test/integration.test.ts) :)
