### ISSUE TITLE
Unhandled promise rejection during reconnect

### ISSUE THREAD

**Issue by Ingramz** [andywer/pg-listen#22]
I'm getting unnecessary console spam from unsuccessful reconnect attempts that seem to be caused by the rejection on [this line](https://github.com/andywer/pg-listen/blob/42119594095b1804dead13091b7b37e2aa5d6f25/src/index.ts#L102).

To cause temporary interruptions I used the following SQL. For the grant/revoke to work, the user which connection is being interrupted must not be a superuser. This is probably not the only way to cause an interruption, it could be also at the network level or by temporarily shutting down the database. Setting `retryTimeout` to a null value is useful as well.
```pgsql
-- Revoke new connections for non-superusers
REVOKE CONNECT ON DATABASE mydatabase FROM public;
-- Terminate currently active connections for a specific non-superuser 'myuser'
SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid() AND usename = 'myuser';
-- Some time later restore ability to reconnect
GRANT CONNECT ON DATABASE mydatabase TO public;
```

I couldn't really understand in which state `end` is called in relation to the try/catch block where this code is placed, so I am unsure what the supposed fix should be.

Here's what I'm getting in console:
<details>

```
(node:14040) UnhandledPromiseRejectionWarning: Error: Connection ended.
    at Client.<anonymous> (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg-listen\dist\index.js:89:93)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:198:13)
    at process.nextTick (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg\lib\client.js:256:12)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:14040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14040) UnhandledPromiseRejectionWarning: Error: Connection ended.
    at Client.<anonymous> (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg-listen\dist\index.js:89:93)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:198:13)
    at process.nextTick (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg\lib\client.js:256:12)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:14040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14040) UnhandledPromiseRejectionWarning: Error: Connection ended.
    at Client.<anonymous> (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg-listen\dist\index.js:89:93)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:198:13)
    at process.nextTick (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg\lib\client.js:256:12)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:14040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14040) UnhandledPromiseRejectionWarning: Error: Connection ended.
    at Client.<anonymous> (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg-listen\dist\index.js:89:93)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:198:13)
    at process.nextTick (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg\lib\client.js:256:12)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:14040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:14040) UnhandledPromiseRejectionWarning: Error: Connection ended.
    at Client.<anonymous> (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg-listen\dist\index.js:89:93)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:198:13)
    at process.nextTick (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg\lib\client.js:256:12)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:14040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:14040) UnhandledPromiseRejectionWarning: Error: Connection ended.
    at Client.<anonymous> (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg-listen\dist\index.js:89:93)
    at Object.onceWrapper (events.js:286:20)
    at Client.emit (events.js:198:13)
    at process.nextTick (C:\Users\Indrek\Desktop\node-indexer\node_modules\pg\lib\client.js:256:12)
    at process._tickCallback (internal/process/next_tick.js:61:11)
...repeat...
```
</details>

**Comment by andywer** [comment]
Hey @Ingramz!

Thanks for reporting. Yeah, the code is not exactly a beauty, I have to admit.
Anyhow, I might have a fix for the issue, haven't tested it though.

Can you `npm i pg-listen@1.3.0-unhandled-rejection-fix` and see if it fixes the issue?

The fix can be found on this branch: [`bugfix/22-unhandled-rejection`](https://github.com/andywer/pg-listen/tree/bugfix/22-unhandled-rejection)

Basically I just replaced two consecutive `await` that refer to very tightly coupled promises with one `await Promise.all()` handling both of them, so the second promise is assigned a rejection handler right away and not just after the first promise succeeded.

**Comment by Ingramz** [comment]
@andywer thank you for reacting so quickly ⚡️. I can confirm that this change has indeed solved it my case.
