### ISSUE TITLE
division by zero error

### ISSUE THREAD

**Issue by mako-taco** [andywer/pg-listen#49]
Periodically having this thrown:

```
error: division by zero
    at Parser.parseErrorMessage (/var/app/current/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/var/app/current/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/var/app/current/node_modules/pg-protocol/src/parser.ts:101:30)
    at Socket.<anonymous> (/var/app/current/node_modules/pg-protocol/src/index.ts:7:48)
    at /var/app/current/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
    at Scope._activate (/var/app/current/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)
    at Scope.activate (/var/app/current/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
    at Socket.bound (/var/app/current/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

I can work on a minimal repro if its helpful.

Strangely enough, I am not even connecting to the database, or starting to listen on any channels. The only thing I need to do to produce this error is import the module.

**Comment by mako-taco** [comment]
wow I cant read! wrong library. sorry!

**Comment by andywer** [comment]
No worries! 😄
